In [3]:
#Import Dependencies
import pandas as pd
import sqlite3
from sqlite3 import Error

In [4]:
# Read in CSVs from folder structure: <POSITION>_stats/
#List of positions
position = ['QB', 'RB', 'TE', 'WR']
#years 
year = [2018, 2019, 2020, 2021]
#empty list for df names created
df_names =[]
#dempty list to hold dfs
df_list = []

#loop through to read csv files to dfs
for x in position: 
    pos= x.lower()
    for y in year:
        filename = f"advanced-{pos}-metrics{y}.csv"
        filepath = f"../DataBase/Resources/{x}_stats/"
        df = f"{pos}_{y}_df"
        df_names.append(df)
        read_df = pd.read_csv(f"{filepath}{filename}")
        df_list.append(read_df)

In [5]:
#Check df names
df_names

['qb_2018_df',
 'qb_2019_df',
 'qb_2020_df',
 'qb_2021_df',
 'rb_2018_df',
 'rb_2019_df',
 'rb_2020_df',
 'rb_2021_df',
 'te_2018_df',
 'te_2019_df',
 'te_2020_df',
 'te_2021_df',
 'wr_2018_df',
 'wr_2019_df',
 'wr_2020_df',
 'wr_2021_df']

In [6]:
#check data list 
len(df_list)

16

In [7]:
#Add year series to each dataframe
for i in range(0,len(df_list)):
    yr = df_names[i][3:7]
    df_list[i]["Year"] = yr

In [8]:
#Check year was added
df_list[1].head()

,Rank,PlayerPlayerId,PlayerShortName,PlayerAgeExact,PassAttemptsPerGame,PassingYards,CompletionPercentage,PassingTouchdowns,Interceptions,MoneyThrows,TouchdownRate,ProtectionRate,PressuredCompletionPercentage,AirYards,AirYardsPerGame,AirYardsPerAttempt,DeepBallAttempts,DeepBallCompletionPercentage,Year
0,1,19781,L. Jackson,25.5,26.7,3127,66.1,36,6,19,9.0,87.3,34.7,1883.0,125.5,4.7,60,33.3,2019
1,2,18055,D. Prescott,28.9,37.2,4901,65.1,30,11,23,5.0,85.8,33.1,3098.0,193.6,5.2,78,48.7,2019
2,3,14536,R. Wilson,33.6,32.2,4111,66.1,31,5,33,6.0,78.2,33.3,2521.0,157.6,4.9,83,39.8,2019
3,4,18857,D. Watson,26.8,33.0,3852,67.3,26,12,24,5.3,84.8,44.8,2284.0,152.3,4.6,81,42.0,2019
4,5,16762,J. Winston,28.5,39.1,5109,60.7,33,30,19,5.3,82.8,37.2,3248.0,203.0,5.2,113,36.3,2019

In [9]:
#Create empty DF to concatenate position
qb_df = pd.DataFrame()
rb_df = pd.DataFrame()
te_df = pd.DataFrame()
wr_df = pd.DataFrame()

In [10]:
#Use coniditionals to concat dataframs
for i in range(0,len(df_list)):
    #Check for QB name
    if df_names[i][:2] == 'qb': 
        qb_df = pd.concat([df_list[i], qb_df], ignore_index=True)
        print(f"index {i} was added to qb")
    #Check for RB name / Add to DF
    elif df_names[i][:2] == 'rb':
        rb_df = pd.concat([df_list[i], rb_df], ignore_index=True)
        print(f"index {i} was added to rb")
    #Check for TE name / Add to DF
    elif df_names[i][:2] == 'te': 
        te_df = pd.concat([df_list[i], te_df], ignore_index=True)
        print(f"index {i} was added to te")
    #Check for WR name / Add to DF
    elif df_names[i][:2] == 'wr': 
        wr_df = pd.concat([df_list[i], wr_df], ignore_index=True)
        print(f"index {i} was added to wr")
    #Check for mistakes
    else:
        print("Uh Oh!")

index 0 was added to qb
index 1 was added to qb
index 2 was added to qb
index 3 was added to qb
index 4 was added to rb
index 5 was added to rb
index 6 was added to rb
index 7 was added to rb
index 8 was added to te
index 9 was added to te
index 10 was added to te
index 11 was added to te
index 12 was added to wr
index 13 was added to wr
index 14 was added to wr
index 15 was added to wr

In [11]:
#Quick Check on QBs
qb_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 131 entries, 0 to 130
Data columns (total 19 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Rank                           131 non-null    int64
 1   PlayerPlayerId                 131 non-null    int64
 2   PlayerShortName                131 non-null    object
 3   PlayerAgeExact                 131 non-null    float64
 4   PassAttemptsPerGame            131 non-null    float64
 5   PassingYards                   131 non-null    int64
 6   CompletionPercentage           131 non-null    float64
 7   PassingTouchdowns              131 non-null    int64
 8   Interceptions                  131 non-null    int64
 9   MoneyThrows                    131 non-null    int64
 10  TouchdownRate                  131 non-null    float64
 11  ProtectionRate                 131 non-null    float64
 12  PressuredCompletionPercentage  131 non-null    float64
 13  AirYards                       131 non-null    float64
 14  AirYardsPerGame                131 non-null    float64
 15  AirYardsPerAttempt             131 non-null    float64
 16  DeepBallAttempts               131 non-null    int64
 17  DeepBallCompletionPercentage   131 non-null    float64
 18  Year                           131 non-null    object
dtypes: float64(10), int64(7), object(2)
memory usage: 19.6+ KB

In [12]:
#Quick Check on TEs
te_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 116 entries, 0 to 115
Data columns (total 20 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Rank                    116 non-null    int64
 1   PlayerPlayerId          116 non-null    int64
 2   PlayerShortName         116 non-null    object
 3   Targets                 116 non-null    int64
 4   Receptions              116 non-null    int64
 5   ReceivingYards          116 non-null    int64
 6   ReceivingTDs            116 non-null    int64
 7   HogRate                 2 non-null      float64
 8   SnapShare               116 non-null    float64
 9   AverageTargetDistance   116 non-null    float64
 10  AirYards                116 non-null    float64
 11  AirYardsPerGame         116 non-null    float64
 12  AirYardsPerReception    116 non-null    float64
 13  Targets.1               116 non-null    int64
 14  RedZoneTargets          116 non-null    int64
 15  EndzoneTargets          116 non-null    int64
 16  TargetAccuracy          116 non-null    float64
 17  TargetShare             116 non-null    float64
 18  FantasyPointsPerTarget  116 non-null    float64
 19  Year                    116 non-null    object
dtypes: float64(9), int64(9), object(2)
memory usage: 18.2+ KB

In [13]:
#Quick Check on WR
wr_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 340 entries, 0 to 339
Data columns (total 20 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Rank                    340 non-null    int64
 1   PlayerPlayerId          340 non-null    int64
 2   PlayerShortName         340 non-null    object
 3   Targets                 340 non-null    int64
 4   Receptions              340 non-null    int64
 5   ReceivingYards          340 non-null    int64
 6   ReceivingTDs            340 non-null    int64
 7   HogRate                 14 non-null     float64
 8   SnapShare               340 non-null    float64
 9   AverageTargetDistance   340 non-null    float64
 10  AirYards                340 non-null    float64
 11  AirYardsPerGame         340 non-null    float64
 12  AirYardsPerReception    340 non-null    float64
 13  Targets.1               340 non-null    int64
 14  RedZoneTargets          340 non-null    int64
 15  EndzoneTargets          340 non-null    int64
 16  TargetAccuracy          340 non-null    float64
 17  TargetShare             340 non-null    float64
 18  FantasyPointsPerTarget  340 non-null    float64
 19  Year                    340 non-null    object
dtypes: float64(9), int64(9), object(2)
memory usage: 53.2+ KB

In [14]:
#Quick Check on RBs
rb_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 649 entries, 0 to 648
Data columns (total 23 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Rank                      649 non-null    int64
 1   PlayerPlayerId            649 non-null    int64
 2   PlayerShortName           649 non-null    object
 3   PlayerAgeExact            649 non-null    float64
 4   Carries                   649 non-null    int64
 5   RushingYards              649 non-null    int64
 6   YardsPerCarry             613 non-null    float64
 7   RushingTouchdowns         649 non-null    int64
 8   Targets                   649 non-null    int64
 9   Receptions                649 non-null    int64
 10  ReceivingYards            649 non-null    int64
 11  ReceivingTDs              649 non-null    int64
 12  SnapShare                 649 non-null    float64
 13  OpportunityShare          637 non-null    float64
 14  ShotgunCarryRate          585 non-null    float64
 15  ShotgunYardsPerCarry      576 non-null    float64
 16  UnderCenterCarryRate      585 non-null    float64
 17  UnderCenterYardsPerCarry  603 non-null    float64
 18  AverageDefendersInTheBox  585 non-null    float64
 19  StackedFrontCarryRate     585 non-null    float64
 20  BaseFrontCarryRate        585 non-null    float64
 21  LightFrontCarryRate       585 non-null    float64
 22  Year                      649 non-null    object
dtypes: float64(12), int64(9), object(2)
memory usage: 116.7+ KB

In [15]:
#Add position column to each DF
rb_df["Position"] = "RB"
qb_df["Position"] = "QB"
wr_df["Position"] = "WR"
te_df["Position"] = "TE"

In [16]:
#Read in Teams DF
teams_df = pd.read_csv("../DataBase/Resources/Teams.csv", index_col=0)
teams_df

                          Name Abbreviation Conference Division  Unnamed: 5
ID
1.0          Arizona Cardinals          ARI        NFC     West         NaN
2.0            Atlanta Falcons          ATL        NFC    South         NaN
3.0           Baltimore Ravens          BAL        AFC    North         NaN
4.0              Buffalo Bills          BUF        AFC     East         NaN
5.0          Carolina Panthers          CAR        NFC    South         NaN
6.0              Chicago Bears          CHI        NFC    North         NaN
7.0         Cincinnati Bengals          CIN        AFC    North         NaN
8.0           Cleveland Browns          CLE        AFC    North         NaN
9.0             Dallas Cowboys          DAL        NFC     East         NaN
10.0            Denver Broncos          DEN        AFC     West         NaN
11.0             Detroit Lions          DET        NFC    North         NaN
12.0         Green Bay Packers           GB        NFC    North         NaN
13.0            Houston Texans          HOU        AFC    South         NaN
14.0        Indianapolis Colts          IND        AFC    South         NaN
15.0      Jacksonville Jaguars          JAX        AFC    South         NaN
16.0        Kansas City Chiefs           KC        AFC     West         NaN
17.0            Miami Dolphins          MIA        AFC     East         NaN
18.0         Minnesota Vikings          MIN        NFC    North         NaN
19.0      New England Patriots           NE        AFC     East         NaN
20.0        New Orleans Saints           NO        NFC    South         NaN
21.0                 NY Giants          NYG        NFC     East         NaN
22.0                   NY Jets          NYJ        AFC     East         NaN
23.0         Las Vegas Raiders           LV        AFC     West         NaN
24.0       Philadelphia Eagles          PHI        NFC     East         NaN
25.0       Pittsburgh Steelers          PIT        AFC    North         NaN
26.0      Los Angeles Chargers          LAC        AFC     West         NaN
27.0       San Francisco 49ers           SF        NFC     West         NaN
28.0          Seattle Seahawks          SEA        NFC     West         NaN
29.0          Los Angeles Rams          LAR        NFC     West         NaN
30.0      Tampa Bay Buccaneers           TB        NFC    South         NaN
31.0          Tennessee Titans          TEN        AFC    South         NaN
32.0  Washington Football Team          WAS        NFC     East         NaN
NaN                        NaN          NaN        NaN      NaN         NaN
NaN                        NaN          NaN        NaN      NaN         NaN
NaN                        NaN          NaN        NaN      NaN         NaN
NaN                        NaN          NaN        NaN      NaN         NaN
NaN                        NaN          NaN        NaN      NaN         NaN
NaN                        NaN          NaN        NaN      NaN         NaN
NaN                        NaN          NaN        NaN      NaN         NaN
NaN                        NaN          NaN        NaN      NaN         NaN
NaN                        NaN          NaN        NaN      NaN         NaN
NaN                        NaN          NaN        NaN      NaN         NaN
NaN                        NaN          NaN        NaN      NaN         NaN
NaN                        NaN          NaN        NaN      NaN         NaN
NaN                        NaN          NaN        NaN      NaN         NaN

In [17]:
#Remove unnamed column
teams_df = teams_df.loc[:, ~teams_df.columns.str.contains('^Unnamed')]

In [18]:
#remove extra rows
teams_df.dropna(axis = 0, inplace=True)

c:\Users\camke\anaconda3\envs\PythonData\lib\site-packages\pandas\util\_decorators.py:311: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return func(*args, **kwargs)

In [19]:
#Check clean up
teams_df

                          Name Abbreviation Conference Division
ID
1.0          Arizona Cardinals          ARI        NFC     West
2.0            Atlanta Falcons          ATL        NFC    South
3.0           Baltimore Ravens          BAL        AFC    North
4.0              Buffalo Bills          BUF        AFC     East
5.0          Carolina Panthers          CAR        NFC    South
6.0              Chicago Bears          CHI        NFC    North
7.0         Cincinnati Bengals          CIN        AFC    North
8.0           Cleveland Browns          CLE        AFC    North
9.0             Dallas Cowboys          DAL        NFC     East
10.0            Denver Broncos          DEN        AFC     West
11.0             Detroit Lions          DET        NFC    North
12.0         Green Bay Packers           GB        NFC    North
13.0            Houston Texans          HOU        AFC    South
14.0        Indianapolis Colts          IND        AFC    South
15.0      Jacksonville Jaguars          JAX        AFC    South
16.0        Kansas City Chiefs           KC        AFC     West
17.0            Miami Dolphins          MIA        AFC     East
18.0         Minnesota Vikings          MIN        NFC    North
19.0      New England Patriots           NE        AFC     East
20.0        New Orleans Saints           NO        NFC    South
21.0                 NY Giants          NYG        NFC     East
22.0                   NY Jets          NYJ        AFC     East
23.0         Las Vegas Raiders           LV        AFC     West
24.0       Philadelphia Eagles          PHI        NFC     East
25.0       Pittsburgh Steelers          PIT        AFC    North
26.0      Los Angeles Chargers          LAC        AFC     West
27.0       San Francisco 49ers           SF        NFC     West
28.0          Seattle Seahawks          SEA        NFC     West
29.0          Los Angeles Rams          LAR        NFC     West
30.0      Tampa Bay Buccaneers           TB        NFC    South
31.0          Tennessee Titans          TEN        AFC    South
32.0  Washington Football Team          WAS        NFC     East

In [20]:
#Read in full quick stats
fullQuickStats = pd.read_csv("../DataBase/Resources/FullPlayerQuickStats.csv")
fullQuickStats.head()

,Rank,PlayerID,Name,Team,Position,Played,FantasyPointsPerGame,FantasyPoints,Unnamed: 8
0,1,19801,Josh Allen,BUF,QB,17,23.7,402.58,NaN
1,2,21681,Justin Herbert,LAC,QB,17,22.4,380.76,NaN
2,3,4314,Tom Brady,TB,QB,17,22.0,374.74,NaN
3,4,18890,Patrick Mahomes,KC,QB,17,21.3,361.66,NaN
4,5,21682,Jonathan Taylor,IND,RB,17,19.6,333.10,NaN

In [21]:
#Clean Up 
fullQuickStats = fullQuickStats.loc[:, ~fullQuickStats.columns.str.contains('^Unnamed')]
fullQuickStats.dropna(axis = 0, inplace=True)

In [22]:
fullQuickStats.head()

,Rank,PlayerID,Name,Team,Position,Played,FantasyPointsPerGame,FantasyPoints
0,1,19801,Josh Allen,BUF,QB,17,23.7,402.58
1,2,21681,Justin Herbert,LAC,QB,17,22.4,380.76
2,3,4314,Tom Brady,TB,QB,17,22.0,374.74
3,4,18890,Patrick Mahomes,KC,QB,17,21.3,361.66
4,5,21682,Jonathan Taylor,IND,RB,17,19.6,333.10

In [23]:
qb_df_copy = qb_df.copy()

In [24]:
qb_df_copy.head()

,Rank,PlayerPlayerId,PlayerShortName,PlayerAgeExact,PassAttemptsPerGame,PassingYards,CompletionPercentage,PassingTouchdowns,Interceptions,MoneyThrows,TouchdownRate,ProtectionRate,PressuredCompletionPercentage,AirYards,AirYardsPerGame,AirYardsPerAttempt,DeepBallAttempts,DeepBallCompletionPercentage,Year,Position
0,1,19801,J. Allen,26.1,37.9,4407,63.41,36,15,29,5.58,77.94,37.83,2785.0,163.82,4.31,80,42.50,2021,QB
1,2,21681,J. Herbert,24.3,39.5,5014,65.92,38,15,30,5.65,88.62,41.34,2678.0,157.52,3.98,71,43.66,2021,QB
2,3,4314,T. Brady,44.9,42.3,5316,67.45,43,12,44,5.98,92.98,46.84,2792.0,164.23,3.88,87,40.22,2021,QB
3,4,18890,P. Mahomes,26.8,38.7,4839,66.26,37,13,32,5.62,85.27,40.65,2219.0,130.52,3.37,79,36.70,2021,QB
4,5,9038,M. Stafford,34.4,35.4,4886,67.22,41,17,33,6.82,86.37,53.84,2831.0,166.52,4.71,71,42.25,2021,QB

In [25]:
fullQuickStats = fullQuickStats.rename(columns = {"PlayerID": "PlayerPlayerID"})

QB Clean up

In [26]:
qb_df.head()

,Rank,PlayerPlayerId,PlayerShortName,PlayerAgeExact,PassAttemptsPerGame,PassingYards,CompletionPercentage,PassingTouchdowns,Interceptions,MoneyThrows,TouchdownRate,ProtectionRate,PressuredCompletionPercentage,AirYards,AirYardsPerGame,AirYardsPerAttempt,DeepBallAttempts,DeepBallCompletionPercentage,Year,Position
0,1,19801,J. Allen,26.1,37.9,4407,63.41,36,15,29,5.58,77.94,37.83,2785.0,163.82,4.31,80,42.50,2021,QB
1,2,21681,J. Herbert,24.3,39.5,5014,65.92,38,15,30,5.65,88.62,41.34,2678.0,157.52,3.98,71,43.66,2021,QB
2,3,4314,T. Brady,44.9,42.3,5316,67.45,43,12,44,5.98,92.98,46.84,2792.0,164.23,3.88,87,40.22,2021,QB
3,4,18890,P. Mahomes,26.8,38.7,4839,66.26,37,13,32,5.62,85.27,40.65,2219.0,130.52,3.37,79,36.70,2021,QB
4,5,9038,M. Stafford,34.4,35.4,4886,67.22,41,17,33,6.82,86.37,53.84,2831.0,166.52,4.71,71,42.25,2021,QB

In [27]:
qb_df = qb_df.rename(columns = {"PlayerPlayerId": "PlayerID"})
qb_df.head()

,Rank,PlayerID,PlayerShortName,PlayerAgeExact,PassAttemptsPerGame,PassingYards,CompletionPercentage,PassingTouchdowns,Interceptions,MoneyThrows,TouchdownRate,ProtectionRate,PressuredCompletionPercentage,AirYards,AirYardsPerGame,AirYardsPerAttempt,DeepBallAttempts,DeepBallCompletionPercentage,Year,Position
0,1,19801,J. Allen,26.1,37.9,4407,63.41,36,15,29,5.58,77.94,37.83,2785.0,163.82,4.31,80,42.50,2021,QB
1,2,21681,J. Herbert,24.3,39.5,5014,65.92,38,15,30,5.65,88.62,41.34,2678.0,157.52,3.98,71,43.66,2021,QB
2,3,4314,T. Brady,44.9,42.3,5316,67.45,43,12,44,5.98,92.98,46.84,2792.0,164.23,3.88,87,40.22,2021,QB
3,4,18890,P. Mahomes,26.8,38.7,4839,66.26,37,13,32,5.62,85.27,40.65,2219.0,130.52,3.37,79,36.70,2021,QB
4,5,9038,M. Stafford,34.4,35.4,4886,67.22,41,17,33,6.82,86.37,53.84,2831.0,166.52,4.71,71,42.25,2021,QB

In [28]:
qb_df.isnull().sum()

Rank                             0
PlayerID                         0
PlayerShortName                  0
PlayerAgeExact                   0
PassAttemptsPerGame              0
PassingYards                     0
CompletionPercentage             0
PassingTouchdowns                0
Interceptions                    0
MoneyThrows                      0
TouchdownRate                    0
ProtectionRate                   0
PressuredCompletionPercentage    0
AirYards                         0
AirYardsPerGame                  0
AirYardsPerAttempt               0
DeepBallAttempts                 0
DeepBallCompletionPercentage     0
Year                             0
Position                         0
dtype: int64

In [29]:
qb_df = qb_df.rename(columns = {"PlayerAgeExact": "Age"})
qb_df.head()

,Rank,PlayerID,PlayerShortName,Age,PassAttemptsPerGame,PassingYards,CompletionPercentage,PassingTouchdowns,Interceptions,MoneyThrows,TouchdownRate,ProtectionRate,PressuredCompletionPercentage,AirYards,AirYardsPerGame,AirYardsPerAttempt,DeepBallAttempts,DeepBallCompletionPercentage,Year,Position
0,1,19801,J. Allen,26.1,37.9,4407,63.41,36,15,29,5.58,77.94,37.83,2785.0,163.82,4.31,80,42.50,2021,QB
1,2,21681,J. Herbert,24.3,39.5,5014,65.92,38,15,30,5.65,88.62,41.34,2678.0,157.52,3.98,71,43.66,2021,QB
2,3,4314,T. Brady,44.9,42.3,5316,67.45,43,12,44,5.98,92.98,46.84,2792.0,164.23,3.88,87,40.22,2021,QB
3,4,18890,P. Mahomes,26.8,38.7,4839,66.26,37,13,32,5.62,85.27,40.65,2219.0,130.52,3.37,79,36.70,2021,QB
4,5,9038,M. Stafford,34.4,35.4,4886,67.22,41,17,33,6.82,86.37,53.84,2831.0,166.52,4.71,71,42.25,2021,QB

In [30]:
len(qb_df["PlayerID"].unique())

55

Running Back clean up

In [31]:
rb_df.head()

,Rank,PlayerPlayerId,PlayerShortName,PlayerAgeExact,Carries,RushingYards,YardsPerCarry,RushingTouchdowns,Targets,Receptions,...,ShotgunCarryRate,ShotgunYardsPerCarry,UnderCenterCarryRate,UnderCenterYardsPerCarry,AverageDefendersInTheBox,StackedFrontCarryRate,BaseFrontCarryRate,LightFrontCarryRate,Year,Position
0,1,21682,J. Taylor,23.5,332,1811,5.45,18,53,40,...,37.65,1.0,62.34,1.0,6.07,13.25,28.31,57.83,2021,RB
1,2,19798,N. Chubb,26.5,228,1259,5.52,8,25,20,...,15.35,1.0,84.64,1.0,6.98,28.07,44.73,25.87,2021,RB
2,3,18858,J. Mixon,26.0,292,1205,4.12,13,48,42,...,25.34,1.0,74.65,1.0,6.69,17.80,34.93,47.26,2021,RB
3,4,21768,N. Harris,24.3,307,1200,3.90,7,94,74,...,52.44,1.0,46.57,1.0,6.52,16.93,29.64,50.81,2021,RB
4,5,18872,D. Cook,26.9,249,1159,4.65,6,49,34,...,18.07,1.0,81.92,1.0,6.87,20.88,46.18,32.53,2021,RB

In [32]:
rb_df = rb_df.rename(columns = {"PlayerPlayerId": "PlayerID", "PlayerAgeExact": "Age"})
rb_df.head()

,Rank,PlayerID,PlayerShortName,Age,Carries,RushingYards,YardsPerCarry,RushingTouchdowns,Targets,Receptions,...,ShotgunCarryRate,ShotgunYardsPerCarry,UnderCenterCarryRate,UnderCenterYardsPerCarry,AverageDefendersInTheBox,StackedFrontCarryRate,BaseFrontCarryRate,LightFrontCarryRate,Year,Position
0,1,21682,J. Taylor,23.5,332,1811,5.45,18,53,40,...,37.65,1.0,62.34,1.0,6.07,13.25,28.31,57.83,2021,RB
1,2,19798,N. Chubb,26.5,228,1259,5.52,8,25,20,...,15.35,1.0,84.64,1.0,6.98,28.07,44.73,25.87,2021,RB
2,3,18858,J. Mixon,26.0,292,1205,4.12,13,48,42,...,25.34,1.0,74.65,1.0,6.69,17.80,34.93,47.26,2021,RB
3,4,21768,N. Harris,24.3,307,1200,3.90,7,94,74,...,52.44,1.0,46.57,1.0,6.52,16.93,29.64,50.81,2021,RB
4,5,18872,D. Cook,26.9,249,1159,4.65,6,49,34,...,18.07,1.0,81.92,1.0,6.87,20.88,46.18,32.53,2021,RB

In [38]:
rb_df.isnull().sum()

Rank                         0
PlayerID                     0
PlayerShortName              0
Age                          0
Carries                      0
RushingYards                 0
YardsPerCarry                0
RushingTouchdowns            0
Targets                      0
Receptions                   0
ReceivingYards               0
ReceivingTDs                 0
SnapShare                    0
OpportunityShare            12
ShotgunCarryRate            64
ShotgunYardsPerCarry        73
UnderCenterCarryRate        64
UnderCenterYardsPerCarry    46
AverageDefendersInTheBox    64
StackedFrontCarryRate       64
BaseFrontCarryRate          64
LightFrontCarryRate         64
Year                         0
Position                     0
dtype: int64

In [34]:
len(rb_df["PlayerID"].unique())

274

In [36]:
rb_df[rb_df["YardsPerCarry"].isnull()]

rb_df["YardsPerCarry"].fillna(rb_df["RushingYards"] / rb_df["Carries"], inplace=True)
rb_df["YardsPerCarry"].fillna(value = 0, inplace = True)

In [37]:
rb_df[rb_df["Carries"] == 0].count()

Rank                        54
PlayerID                    54
PlayerShortName             54
Age                         54
Carries                     54
RushingYards                54
YardsPerCarry               54
RushingTouchdowns           54
Targets                     54
Receptions                  54
ReceivingYards              54
ReceivingTDs                54
SnapShare                   54
OpportunityShare            52
ShotgunCarryRate             0
ShotgunYardsPerCarry        28
UnderCenterCarryRate         0
UnderCenterYardsPerCarry    28
AverageDefendersInTheBox     0
StackedFrontCarryRate        0
BaseFrontCarryRate           0
LightFrontCarryRate          0
Year                        54
Position                    54
dtype: int64

In [39]:
null_columns = ["LightFrontCarryRate", "BaseFrontCarryRate", "StackedFrontCarryRate", "UnderCenterYardsPerCarry", "UnderCenterCarryRate", "ShotgunYardsPerCarry", "ShotgunCarryRate"]

In [45]:
for column in null_columns: 
     rb_df[rb_df["Carries"] == 0] = rb_df[rb_df["Carries"] == 0].fillna(value = 0)

In [46]:
rb_df[rb_df["Carries"] == 0].count()

Rank                        54
PlayerID                    54
PlayerShortName             54
Age                         54
Carries                     54
RushingYards                54
YardsPerCarry               54
RushingTouchdowns           54
Targets                     54
Receptions                  54
ReceivingYards              54
ReceivingTDs                54
SnapShare                   54
OpportunityShare            54
ShotgunCarryRate            54
ShotgunYardsPerCarry        54
UnderCenterCarryRate        54
UnderCenterYardsPerCarry    54
AverageDefendersInTheBox    54
StackedFrontCarryRate       54
BaseFrontCarryRate          54
LightFrontCarryRate         54
Year                        54
Position                    54
dtype: int64

In [47]:
rb_df.isnull().sum()

Rank                         0
PlayerID                     0
PlayerShortName              0
Age                          0
Carries                      0
RushingYards                 0
YardsPerCarry                0
RushingTouchdowns            0
Targets                      0
Receptions                   0
ReceivingYards               0
ReceivingTDs                 0
SnapShare                    0
OpportunityShare            10
ShotgunCarryRate            10
ShotgunYardsPerCarry        10
UnderCenterCarryRate        10
UnderCenterYardsPerCarry    10
AverageDefendersInTheBox    10
StackedFrontCarryRate       10
BaseFrontCarryRate          10
LightFrontCarryRate         10
Year                         0
Position                     0
dtype: int64

In [59]:
rb_df[rb_df["OpportunityShare"].isnull()]

,Rank,PlayerID,PlayerShortName,Age,Carries,RushingYards,YardsPerCarry,RushingTouchdowns,Targets,Receptions,...,ShotgunCarryRate,ShotgunYardsPerCarry,UnderCenterCarryRate,UnderCenterYardsPerCarry,AverageDefendersInTheBox,StackedFrontCarryRate,BaseFrontCarryRate,LightFrontCarryRate,Year,Position
113,114,16855,T. Montgomery,29.5,15,44,2.933333,0,26,16,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2021,RB
125,126,15215,T. Austin,32.3,3,21,7.000000,0,38,24,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2021,RB
228,65,15150,C. Patterson,31.3,64,232,3.625000,1,25,21,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2020,RB
387,55,18464,J. McKissic,28.9,38,205,5.394737,0,42,34,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2019,RB
410,78,15215,T. Austin,32.3,6,47,7.833333,1,24,13,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2019,RB
426,94,15150,C. Patterson,31.3,17,103,6.058824,0,17,11,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2019,RB
531,43,15126,T. Riddick,31.2,40,171,4.275000,0,75,61,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018,RB
542,54,15150,C. Patterson,31.3,42,228,5.428571,1,28,21,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018,RB
574,86,15215,T. Austin,32.3,6,55,9.166667,0,13,8,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018,RB
640,152,18464,J. McKissic,28.9,3,8,2.666667,0,1,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018,RB

In [66]:
rb_df[rb_df.isnull()]["PlayerShortName"].value_counts()

Series([], Name: PlayerShortName, dtype: int64)

In [64]:
rb_df

,Rank,PlayerID,PlayerShortName,Age,Carries,RushingYards,YardsPerCarry,RushingTouchdowns,Targets,Receptions,...,ShotgunCarryRate,ShotgunYardsPerCarry,UnderCenterCarryRate,UnderCenterYardsPerCarry,AverageDefendersInTheBox,StackedFrontCarryRate,BaseFrontCarryRate,LightFrontCarryRate,Year,Position
0,1,21682,J. Taylor,23.5,332,1811,5.45,18,53,40,...,37.65,1.0,62.34,1.0,6.07,13.25,28.31,57.83,2021,RB
1,2,19798,N. Chubb,26.5,228,1259,5.52,8,25,20,...,15.35,1.0,84.64,1.0,6.98,28.07,44.73,25.87,2021,RB
2,3,18858,J. Mixon,26.0,292,1205,4.12,13,48,42,...,25.34,1.0,74.65,1.0,6.69,17.80,34.93,47.26,2021,RB
3,4,21768,N. Harris,24.3,307,1200,3.90,7,94,74,...,52.44,1.0,46.57,1.0,6.52,16.93,29.64,50.81,2021,RB
4,5,18872,D. Cook,26.9,249,1159,4.65,6,49,34,...,18.07,1.0,81.92,1.0,6.87,20.88,46.18,32.53,2021,RB
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
644,156,16441,S. Perry,30.8,0,0,0.00,0,0,0,...,0.00,0.0,0.00,0.0,0.00,0.00,0.00,0.00,2018,RB
645,157,19078,M. Dayes,27.8,0,0,0.00,0,0,0,...,0.00,0.0,0.00,0.0,0.00,0.00,0.00,0.00,2018,RB
646,158,19626,D. Ogunbowale,28.2,0,0,0.00,0,0,0,...,0.00,0.0,0.00,0.0,0.00,0.00,0.00,0.00,2018,RB
647,159,20039,B. Scott,27.2,0,0,0.00,0,0,0,...,0.00,0.0,0.00,0.0,0.00,0.00,0.00,0.00,2018,RB
648,160,19085,D. Henderson,29.6,2,19,9.50,0,0,0,...,0.00,0.0,100.00,9.5,6.50,0.00,50.00,50.00,2018,RB

In [51]:
rb_df[rb_df["LightFrontCarryRate"].isnull()]['Rank'].min()
#43 is the lowest rank for the

43

In [52]:
wr_df.head()

,Rank,PlayerPlayerId,PlayerShortName,Targets,Receptions,ReceivingYards,ReceivingTDs,HogRate,SnapShare,AverageTargetDistance,...,AirYardsPerGame,AirYardsPerReception,Targets.1,RedZoneTargets,EndzoneTargets,TargetAccuracy,TargetShare,FantasyPointsPerTarget,Year,Position
0,1,18882,C. Kupp,191,145,1947,16,NaN,94.01,8.32,...,93.52,11.0,191,38,11,7.76,31.72,2.30,2021,WR
1,2,16470,D. Adams,169,123,1553,11,NaN,80.33,8.99,...,95.00,12.4,169,28,11,7.33,31.58,2.04,2021,WR
2,3,20932,D. Samuel,120,77,1405,6,NaN,81.44,8.09,...,60.68,12.6,120,10,6,7.14,27.77,2.82,2021,WR
3,4,21685,J. Jefferson,167,108,1616,10,NaN,89.01,11.95,...,117.41,18.5,167,23,15,7.41,29.87,1.98,2021,WR
4,5,22564,J. Chase,128,81,1455,13,NaN,86.11,11.96,...,90.11,18.9,128,12,12,7.30,23.70,2.38,2021,WR

In [53]:
wr_df = wr_df.rename(columns = {"PlayerPlayerId": "PlayerID", "PlayerAgeExact": "Age"})
wr_df.head()

,Rank,PlayerID,PlayerShortName,Targets,Receptions,ReceivingYards,ReceivingTDs,HogRate,SnapShare,AverageTargetDistance,...,AirYardsPerGame,AirYardsPerReception,Targets.1,RedZoneTargets,EndzoneTargets,TargetAccuracy,TargetShare,FantasyPointsPerTarget,Year,Position
0,1,18882,C. Kupp,191,145,1947,16,NaN,94.01,8.32,...,93.52,11.0,191,38,11,7.76,31.72,2.30,2021,WR
1,2,16470,D. Adams,169,123,1553,11,NaN,80.33,8.99,...,95.00,12.4,169,28,11,7.33,31.58,2.04,2021,WR
2,3,20932,D. Samuel,120,77,1405,6,NaN,81.44,8.09,...,60.68,12.6,120,10,6,7.14,27.77,2.82,2021,WR
3,4,21685,J. Jefferson,167,108,1616,10,NaN,89.01,11.95,...,117.41,18.5,167,23,15,7.41,29.87,1.98,2021,WR
4,5,22564,J. Chase,128,81,1455,13,NaN,86.11,11.96,...,90.11,18.9,128,12,12,7.30,23.70,2.38,2021,WR

In [54]:
wr_df.drop(columns=["Targets.1"], inplace =True)

In [55]:
wr_df.head()

,Rank,PlayerID,PlayerShortName,Targets,Receptions,ReceivingYards,ReceivingTDs,HogRate,SnapShare,AverageTargetDistance,AirYards,AirYardsPerGame,AirYardsPerReception,RedZoneTargets,EndzoneTargets,TargetAccuracy,TargetShare,FantasyPointsPerTarget,Year,Position
0,1,18882,C. Kupp,191,145,1947,16,NaN,94.01,8.32,1590.0,93.52,11.0,38,11,7.76,31.72,2.30,2021,WR
1,2,16470,D. Adams,169,123,1553,11,NaN,80.33,8.99,1520.0,95.00,12.4,28,11,7.33,31.58,2.04,2021,WR
2,3,20932,D. Samuel,120,77,1405,6,NaN,81.44,8.09,971.0,60.68,12.6,10,6,7.14,27.77,2.82,2021,WR
3,4,21685,J. Jefferson,167,108,1616,10,NaN,89.01,11.95,1996.0,117.41,18.5,23,15,7.41,29.87,1.98,2021,WR
4,5,22564,J. Chase,128,81,1455,13,NaN,86.11,11.96,1532.0,90.11,18.9,12,12,7.30,23.70,2.38,2021,WR

In [56]:
wr_df.isnull().sum()

Rank                        0
PlayerID                    0
PlayerShortName             0
Targets                     0
Receptions                  0
ReceivingYards              0
ReceivingTDs                0
HogRate                   326
SnapShare                   0
AverageTargetDistance       0
AirYards                    0
AirYardsPerGame             0
AirYardsPerReception        0
RedZoneTargets              0
EndzoneTargets              0
TargetAccuracy              0
TargetShare                 0
FantasyPointsPerTarget      0
Year                        0
Position                    0
dtype: int64

In [57]:
len(wr_df["PlayerID"].unique())

158

In [58]:
wr_df.drop(columns = "HogRate", inplace = True)

TE Clean up

In [68]:
te_df.head()

,Rank,PlayerPlayerId,PlayerShortName,Targets,Receptions,ReceivingYards,ReceivingTDs,HogRate,SnapShare,AverageTargetDistance,...,AirYardsPerGame,AirYardsPerReception,Targets.1,RedZoneTargets,EndzoneTargets,TargetAccuracy,TargetShare,FantasyPointsPerTarget,Year,Position
0,1,19803,M. Andrews,154,107,1361,9,NaN,76.54,9.35,...,84.70,13.5,154,20,13,7.35,26.64,1.96,2021,TE
1,2,15048,T. Kelce,135,92,1125,9,NaN,83.09,7.19,...,60.68,10.6,135,16,4,7.74,22.31,1.95,2021,TE
2,3,19920,D. Schultz,104,78,808,8,NaN,82.59,7.29,...,44.64,9.7,104,14,7,8.17,16.35,2.01,2021,TE
3,4,19063,G. Kittle,95,71,910,6,NaN,92.35,6.70,...,45.50,9.0,95,8,5,7.68,24.86,2.08,2021,TE
4,5,14856,Z. Ertz,112,74,763,5,NaN,70.22,6.67,...,44.00,10.1,112,18,9,6.69,19.31,1.61,2021,TE

In [69]:
te_df.isnull().sum()

Rank                        0
PlayerPlayerId              0
PlayerShortName             0
Targets                     0
Receptions                  0
ReceivingYards              0
ReceivingTDs                0
HogRate                   114
SnapShare                   0
AverageTargetDistance       0
AirYards                    0
AirYardsPerGame             0
AirYardsPerReception        0
Targets.1                   0
RedZoneTargets              0
EndzoneTargets              0
TargetAccuracy              0
TargetShare                 0
FantasyPointsPerTarget      0
Year                        0
Position                    0
dtype: int64

In [70]:
te_df = te_df.rename(columns = {"PlayerPlayerId": "PlayerID", "PlayerAgeExact": "Age"})
te_df.head()

,Rank,PlayerID,PlayerShortName,Targets,Receptions,ReceivingYards,ReceivingTDs,HogRate,SnapShare,AverageTargetDistance,...,AirYardsPerGame,AirYardsPerReception,Targets.1,RedZoneTargets,EndzoneTargets,TargetAccuracy,TargetShare,FantasyPointsPerTarget,Year,Position
0,1,19803,M. Andrews,154,107,1361,9,NaN,76.54,9.35,...,84.70,13.5,154,20,13,7.35,26.64,1.96,2021,TE
1,2,15048,T. Kelce,135,92,1125,9,NaN,83.09,7.19,...,60.68,10.6,135,16,4,7.74,22.31,1.95,2021,TE
2,3,19920,D. Schultz,104,78,808,8,NaN,82.59,7.29,...,44.64,9.7,104,14,7,8.17,16.35,2.01,2021,TE
3,4,19063,G. Kittle,95,71,910,6,NaN,92.35,6.70,...,45.50,9.0,95,8,5,7.68,24.86,2.08,2021,TE
4,5,14856,Z. Ertz,112,74,763,5,NaN,70.22,6.67,...,44.00,10.1,112,18,9,6.69,19.31,1.61,2021,TE

In [71]:
len(te_df["PlayerID"].unique())

59

In [ ]:
te_df.drop(columns= "HogRate", inplace = True)

In [ ]:
bios_df = pd.read_csv("../DataBase/Resources/PlayerBios.csv")
bios_df.head()

In [ ]:
bios_df["experience "] = bios_df["experience"].str[:-9]
bios_df

In [ ]:
bios_df["age"] = bios_df["dob_age"].str[-3:-1]

In [ ]:
bios_df.head()

Start SQL Imports

In [ ]:
#Start SQL connections
con = sqlite3.connect("./sqlite_db.sqlite")

In [ ]:
fullQuickStats.to_sql("QuickStats", con, if_exists="replace")

In [ ]:
qb_df.to_sql("QB_Stats", con, if_exists="replace")
wr_df.to_sql("WR_Stats", con, if_exists="replace")
rb_df.to_sql("RB_Stats", con, if_exists="replace")
te_df.to_sql("TE_Stats", con, if_exists="replace")
teams_df.to_sql("Teams", con, if_exists="replace")
bios_df.to_sql("Player_Bios", con, if_exists='replace')

In [ ]:
cursor = con.cursor()

In [ ]:
# Getting all tables from sqlite_master
sql_query = """SELECT name FROM sqlite_master WHERE type='table';"""

In [ ]:
# executing our sql query
cursor.execute(sql_query)
print("List of tables\n")
    
# printing all tables list
print(cursor.fetchall())