In [1]:
#Import Dependencies
import psycopg2
import sqlalchemy
import pandas as pd 
from config import password

In [2]:
# Read in CSVs
position = ['QB', 'RB', 'TE', 'WR']
year = [2018, 2019, 2020, 2021]
df_names =[]
df_list = []

for x in position: 
    pos= x.lower()
    for y in year:
        filename = f"fantasy-{pos}-leaders{y}.csv"
        filepath = f"../Resources/{x}_stats/"
        df = f"{pos}_{y}_additional_df"
        df_names.append(df)
        read_df = pd.read_csv(f"{filepath}{filename}")
        df_list.append(read_df)

In [3]:
#Check df names
df_names

['qb_2018_additional_df',
 'qb_2019_additional_df',
 'qb_2020_additional_df',
 'qb_2021_additional_df',
 'rb_2018_additional_df',
 'rb_2019_additional_df',
 'rb_2020_additional_df',
 'rb_2021_additional_df',
 'te_2018_additional_df',
 'te_2019_additional_df',
 'te_2020_additional_df',
 'te_2021_additional_df',
 'wr_2018_additional_df',
 'wr_2019_additional_df',
 'wr_2020_additional_df',
 'wr_2021_additional_df']

In [4]:
#check data list 
len(df_list)

16

In [5]:
#Add year to each dataframe
for i in range(0,len(df_list)):
    yr = df_names[i][3:7]
    df_list[i]["Year"] = yr

In [6]:
#Check year was added
df_list[1].head()

,Rank,PlayerID,Name,Team,Position,Played,PassingCompletions,PassingAttempts,PassingCompletionPercentage,PassingYards,...,PassingTouchdowns,PassingInterceptions,PassingRating,RushingAttempts,RushingYards,RushingYardsPerAttempt,RushingTouchdowns,FantasyPointsPerGame,FantasyPoints,Year
0,1,19781,Lamar Jackson,BAL,QB,15,265,401,66.1,3127,...,36,6,113.34,176,1206,6.9,7,27.7,415.68,2019
1,2,18055,Dak Prescott,DAL,QB,16,388,596,65.1,4902,...,30,11,99.69,52,277,5.3,3,21.1,337.78,2019
2,3,14536,Russell Wilson,SEA,QB,16,341,516,66.1,4110,...,31,5,106.33,75,342,4.6,3,20.5,328.60,2019
3,4,18857,Deshaun Watson,HOU,QB,15,333,495,67.3,3852,...,26,12,97.98,82,413,5.0,7,21.3,319.98,2019
4,5,16762,Jameis Winston,TB,QB,16,380,626,60.7,5109,...,33,30,84.28,59,250,4.2,1,19.1,305.36,2019

In [7]:
#Create empty DF to concatenate position
qb_add_df = pd.DataFrame()
rb_add_df = pd.DataFrame()
te_add_df = pd.DataFrame()
wr_add_df = pd.DataFrame()

In [8]:
#Use coniditionals to concat dataframs
for i in range(0,len(df_list)):
    #Check for QB name
    if df_names[i][:2] == 'qb': 
        qb_add_df = pd.concat([df_list[i], qb_add_df], ignore_index=True)
        print(f"index {i} was added to qb")
    #Check for RB name / Add to DF
    elif df_names[i][:2] == 'rb':
        rb_add_df = pd.concat([df_list[i], rb_add_df], ignore_index=True)
        print(f"index {i} was added to rb")
    #Check for TE name / Add to DF
    elif df_names[i][:2] == 'te': 
        te_add_df = pd.concat([df_list[i], te_add_df], ignore_index=True)
        print(f"index {i} was added to te")
    #Check for WR name / Add to DF
    elif df_names[i][:2] == 'wr': 
        wr_add_df = pd.concat([df_list[i], wr_add_df], ignore_index=True)
        print(f"index {i} was added to wr")
    #Check for mistakes
    else:
        print("Uh Oh!")

index 0 was added to qb
index 1 was added to qb
index 2 was added to qb
index 3 was added to qb
index 4 was added to rb
index 5 was added to rb
index 6 was added to rb
index 7 was added to rb
index 8 was added to te
index 9 was added to te
index 10 was added to te
index 11 was added to te
index 12 was added to wr
index 13 was added to wr
index 14 was added to wr
index 15 was added to wr

In [9]:
#Quick Check on QBs
qb_add_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 314 entries, 0 to 313
Data columns (total 21 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Rank                         314 non-null    int64
 1   PlayerID                     314 non-null    int64
 2   Name                         314 non-null    object
 3   Team                         314 non-null    object
 4   Position                     314 non-null    object
 5   Played                       314 non-null    int64
 6   PassingCompletions           314 non-null    int64
 7   PassingAttempts              314 non-null    int64
 8   PassingCompletionPercentage  314 non-null    float64
 9   PassingYards                 314 non-null    int64
 10  PassingYardsPerAttempt       314 non-null    float64
 11  PassingTouchdowns            314 non-null    int64
 12  PassingInterceptions         314 non-null    int64
 13  PassingRating                314 non-null    float64
 14  RushingAttempts              314 non-null    int64
 15  RushingYards                 314 non-null    int64
 16  RushingYardsPerAttempt       314 non-null    float64
 17  RushingTouchdowns            314 non-null    int64
 18  FantasyPointsPerGame         314 non-null    float64
 19  FantasyPoints                314 non-null    float64
 20  Year                         314 non-null    object
dtypes: float64(6), int64(11), object(4)
memory usage: 51.6+ KB

In [10]:
#Quick Check on TEs
te_add_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 566 entries, 0 to 565
Data columns (total 23 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Rank                        566 non-null    int64
 1   PlayerID                    566 non-null    int64
 2   Name                        566 non-null    object
 3   Team                        566 non-null    object
 4   Position                    566 non-null    object
 5   Played                      566 non-null    int64
 6   ReceivingTargets            566 non-null    int64
 7   Receptions                  566 non-null    int64
 8   ReceptionPercentage         566 non-null    float64
 9   ReceivingYards              566 non-null    int64
 10  ReceivingTouchdowns         566 non-null    int64
 11  ReceivingLong               566 non-null    int64
 12  ReceivingYardsPerTarget     566 non-null    float64
 13  ReceivingYardsPerReception  566 non-null    float64
 14  RushingAttempts             566 non-null    int64
 15  RushingYards                566 non-null    int64
 16  RushingYardsPerAttempt      566 non-null    float64
 17  RushingTouchdowns           566 non-null    int64
 18  Fumbles                     566 non-null    int64
 19  FumblesLost                 566 non-null    int64
 20  FantasyPointsPerGame        566 non-null    float64
 21  FantasyPoints               566 non-null    float64
 22  Year                        566 non-null    object
dtypes: float64(6), int64(13), object(4)
memory usage: 101.8+ KB

In [11]:
#Quick Check on WR
wr_add_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 993 entries, 0 to 992
Data columns (total 23 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Rank                        993 non-null    int64
 1   PlayerID                    993 non-null    int64
 2   Name                        993 non-null    object
 3   Team                        993 non-null    object
 4   Position                    993 non-null    object
 5   Played                      993 non-null    int64
 6   ReceivingTargets            993 non-null    int64
 7   Receptions                  993 non-null    int64
 8   ReceptionPercentage         993 non-null    float64
 9   ReceivingYards              993 non-null    int64
 10  ReceivingTouchdowns         993 non-null    int64
 11  ReceivingLong               993 non-null    int64
 12  ReceivingYardsPerTarget     993 non-null    float64
 13  ReceivingYardsPerReception  993 non-null    float64
 14  RushingAttempts             993 non-null    int64
 15  RushingYards                993 non-null    int64
 16  RushingYardsPerAttempt      993 non-null    float64
 17  RushingTouchdowns           993 non-null    int64
 18  Fumbles                     993 non-null    int64
 19  FumblesLost                 993 non-null    int64
 20  FantasyPointsPerGame        993 non-null    float64
 21  FantasyPoints               993 non-null    float64
 22  Year                        993 non-null    object
dtypes: float64(6), int64(13), object(4)
memory usage: 178.6+ KB

In [12]:
#Quick Check on RBs
rb_add_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 704 entries, 0 to 703
Data columns (total 19 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Rank                    704 non-null    int64
 1   PlayerID                704 non-null    int64
 2   Name                    704 non-null    object
 3   Team                    704 non-null    object
 4   Position                704 non-null    object
 5   Played                  704 non-null    int64
 6   RushingAttempts         704 non-null    int64
 7   RushingYards            704 non-null    int64
 8   RushingYardsPerAttempt  704 non-null    float64
 9   RushingTouchdowns       704 non-null    int64
 10  ReceivingTargets        704 non-null    int64
 11  Receptions              704 non-null    int64
 12  ReceivingYards          704 non-null    int64
 13  ReceivingTouchdowns     704 non-null    int64
 14  Fumbles                 704 non-null    int64
 15  FumblesLost             704 non-null    int64
 16  FantasyPointsPerGame    704 non-null    float64
 17  FantasyPoints           704 non-null    float64
 18  Year                    704 non-null    object
dtypes: float64(3), int64(12), object(4)
memory usage: 104.6+ KB

In [13]:
#Add position column to each DF
rb_add_df["position"] = "RB"
qb_add_df["position"] = "QB"
wr_add_df["position"] = "WR"
te_add_df["position"] = "TE"

In [14]:
#format columns for psql to lowercase
qb_add_df.columns= qb_add_df.columns.str.lower()
rb_add_df.columns= rb_add_df.columns.str.lower()
wr_add_df.columns= wr_add_df.columns.str.lower()
te_add_df.columns= te_add_df.columns.str.lower()

In [15]:
qb_add_df.head()

,rank,playerid,name,team,position,played,passingcompletions,passingattempts,passingcompletionpercentage,passingyards,...,passinginterceptions,passingrating,rushingattempts,rushingyards,rushingyardsperattempt,rushingtouchdowns,fantasypointspergame,fantasypoints,year,position
0,1,19801,Josh Allen,BUF,QB,17,409,646,63.3,4407,...,15,92.17,122,763,6.3,6,23.7,402.58,2021,QB
1,2,21681,Justin Herbert,LAC,QB,17,443,672,65.9,5014,...,15,97.66,63,302,4.8,3,22.4,380.76,2021,QB
2,3,4314,Tom Brady,TB,QB,17,485,719,67.5,5316,...,12,102.08,28,81,2.9,2,22.0,374.74,2021,QB
3,4,18890,Patrick Mahomes,KC,QB,17,436,658,66.3,4839,...,13,98.45,66,381,5.8,2,21.3,361.66,2021,QB
4,5,2593,Aaron Rodgers,GB,QB,16,366,531,68.9,4115,...,4,111.90,33,101,3.1,3,20.8,332.30,2021,QB

Start SQL Imports

In [16]:
#Start SQL connections
ENDPOINT="fantasyfootball.ckswyhqaro8q.us-east-2.rds.amazonaws.com"
PORT="5432"
USR="DreamTeam"
PSSWD=password
DBNAME="postgres"

#conn_string = "host='localhost' dbname='my_database' user='postgres' password='secret'
con= "postgresql://{}:{}@{}:{}/{}".format(USR, PSSWD, ENDPOINT, PORT, DBNAME)

In [17]:
#Write dfs to AWS
qb_add_df.to_sql("qb_extra_stats", con, if_exists="replace")
wr_add_df.to_sql("wr_extra_stats", con, if_exists="replace")
rb_add_df.to_sql("rb_extra_stats", con, if_exists="replace")
te_add_df.to_sql("te_extra_stats", con, if_exists="replace")